version: '3'

services:
  postgres:
    container_name: postgres-for-keycloak
    image: docker.io/library/postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5300:5431

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    user: "${UID}"
    volumes:
      - "./car-rental.json:/opt/keycloak/data/import/car-rental.json:Z"
    command:
      - start-dev
      - --import-realm
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 7777:8080
    depends_on:
      - postgres
